Repository tweag/nickel, pull requests merged in 2021-11, with the labels that each got.

#448 save repl history not only on interupt but also when using `:exit` …
  src/repl/rustyline_frontend.rs
Labels: merge-queue

#432 Fix looping typechecking of cyclic imports
  src/cache.rs
  src/repl/mod.rs
  src/transformations.rs
  src/typecheck/mod.rs
  tests/imports.rs
  tests/imports/cycle.ncl
  tests/imports/cycle_b.ncl
Labels: merge-queue

#449 Mention that `--format` also accepts `yaml, toml`
  src/bin/nickel.rs
  src/serialize.rs
Labels: merge-queue

#436 [Language server] Metadata
  lsp/nls/src/linearization.rs
  lsp/nls/src/requests/hover.rs
  src/typecheck/linearization.rs
Labels: merge-queue

#457 [Syntax]Pipe operator (reverse application)
  src/grammar.lalrpop
  src/parser/lexer.rs
  tests/pass/builtins.ncl
Labels: area: syntax

#469 Creating a 2-step process, top-to-bottom and bottom-to-top for transormation phase
  src/term.rs
  src/transformations.rs
Labels: merge-queue

#474 [Stdlib] Add blameWith and fromPred
  examples/config-gcc/config-gcc.ncl
  examples/record-contract/record-contract.ncl
  examples/simple-contracts/README.md
  examples/simple-contracts/simple-contract-bool.ncl
  stdlib/contracts.ncl
Labels: area: contracts

#447 [Language server] Extended Idents
  lsp/nls/src/linearization.rs
  lsp/nls/src/requests/completion.rs
  lsp/nls/src/requests/goto.rs
  lsp/nls/src/requests/hover.rs
  lsp/nls/src/requests/symbols.rs
  lsp/nls/src/server.rs
  src/error.rs
  src/grammar.lalrpop
  src/identifier.rs
  src/label.rs
  src/operation.rs
  src/parser/tests.rs
  src/parser/utils.rs
  src/position.rs
  src/term.rs
  src/transformations.rs
  src/typecheck/linearization.rs
  src/typecheck/mod.rs
  src/types.rs
Labels: merge-queue

#454 [Language server] Properly resolve let and function bindings
  lsp/nls/src/linearization.rs
  lsp/nls/src/requests/hover.rs
  src/typecheck/linearization.rs
  src/typecheck/mod.rs
Labels: merge-queue
