Repository tweag/nickel, pull requests merged in 2021-09, with the labels that each got.

#374 Closed contracts
  src/cache.rs
  src/eval.rs
  src/grammar.lalrpop
  src/merge.rs
  src/operation.rs
  src/parser/lexer.rs
  src/parser/tests.rs
  src/parser/utils.rs
  src/repl/mod.rs
  src/repl/query_print.rs
  src/repl/rustyline_frontend.rs
  src/serialize.rs
  src/term.rs
  src/transformations.rs
  src/typecheck.rs
  src/types.rs
  tests/contracts_fail.rs
  tests/pass/contracts.ncl
Labels: merge-queue, area: contracts

#390 [Fix]Typo in the REPL example of the README
  README.md
Labels: type: documentation

#386 Build the WASM REPL in the flake
  .github/workflows/update-wasm-repl.yml
  .github/workflows/website.yml
  Cargo.lock
  Cargo.toml
  flake.lock
  flake.nix
Labels: merge-queue, area: website

#394 Update flake.lock to account for input renaming
  flake.lock
Labels: merge-queue

#393 Perform imports resolution before typechecking to be able to typecheck the imported files also
  src/cache.rs
  src/eval.rs
  src/program.rs
  src/repl/mod.rs
  src/transformations.rs
  tests/pass/typechecking.ncl
  tests/pass/typed-import.ncl
  tests/typecheck_fail.rs
Labels: merge-queue

#396 add aarch64 platforms
  flake.nix
Labels: merge-queue

#399 Add positional information for unbound type variables
  src/error.rs
  src/grammar.lalrpop
  src/parser/error.rs
  src/parser/tests.rs
  src/parser/utils.rs
Labels: merge-queue

#403 split use modules to be able to compile with --no-default-features
  src/main.rs
Labels: merge-queue

#395 [Fix]Unsound typechecking of imports
  src/typecheck.rs
  tests/pass/typed-import.ncl
  tests/typecheck_fail.rs
Labels: type: bug, merge-queue

#405 Language Server: MVP
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  .vscodeignore
  Cargo.lock
  Cargo.toml
  lsp/client-extension/package-lock.json
  lsp/client-extension/package.json
  lsp/client-extension/src/extension.ts
  lsp/client-extension/tsconfig.json
  lsp/nls/Cargo.toml
  lsp/nls/src/cache.rs
  lsp/nls/src/diagnostic.rs
  lsp/nls/src/files.rs
  lsp/nls/src/main.rs
  lsp/nls/src/server.rs
  src/bin/nickel.rs
  src/cache.rs
  src/error.rs
  src/merge.rs
Labels: merge-queue

#376 Fix dynamic fields not having access to recursive fields
  src/cache.rs
  src/eval.rs
  src/parser/tests.rs
  src/parser/utils.rs
  src/repl/query_print.rs
  src/repl/rustyline_frontend.rs
  src/term.rs
  src/transformations.rs
  src/typecheck.rs
  tests/pass/record-defs.ncl
  tests/pass/typechecking.ncl
  tests/records_fail.rs
  tests/typecheck_fail.rs
Labels: type: bug, merge-queue
