Repository tweag/nickel, pull requests merged in 2022-06, with the labels that each got.

#717 Reduce redundant closurizing when concatenating Arrays.
  src/eval/merge.rs
  src/eval/mod.rs
  src/eval/operation.rs
  src/grammar.lalrpop
  src/pretty.rs
  src/program.rs
  src/serialize.rs
  src/term.rs
  src/transform/free_vars.rs
  src/transform/share_normal_form.rs
  src/typecheck/mod.rs
Labels: run-benchmark

#742 add missing `forall` to `count` function in `benches/nixpkgs/lists.ncl`
  benches/nixpkgs/lists.ncl
Labels: merge-queue

#755 [Fix] Fix use of old row tail syntax in the row polymorphism section of the manual
  doc/manual/typing.md
Labels: type: documentation
