Repository tweag/nickel, pull requests merged in 2022-01, with the labels that each got.

#536 Extend deploy.yml workflow from master branch of the website
  .github/workflows/deploy-preview.yml
Labels: merge-queue

#539 Now quotes are optional for load comand
  src/repl/command.rs
Labels: merge-queue

#485 [User manual] Typing
  doc/manual/cookbook.md
  doc/manual/types-vs-contracts.md
  doc/manual/typing.md
Labels: type: documentation

#542 Fix: #532, only test on rust stable channel
  .github/workflows/continuous-integration.yml
Labels: merge-queue

#544 Fix records benchmark
  benches/lorem.txt
  benches/records/countLetters.ncl
Labels: run-benchmark

#545 Fix: #522, Use eval_full to test examples
  examples/config-gcc/config-gcc.ncl
  src/eval.rs
  src/program.rs
  tests/examples.rs
Labels: merge-queue

#491 Recursive overriding
  lsp/nls/src/linearization.rs
  src/eval.rs
  src/identifier.rs
  src/merge.rs
  src/term.rs
  src/transformations.rs
  src/typecheck/mod.rs
  tests/pass.rs
  tests/pass/overriding.ncl
Labels: merge-queue

#546 Fix expect 'import not found' message in type_check_
  src/typecheck/mod.rs
Labels: merge-queue

#540 Get apparent type from imported term instead of defaulting to Dyn
  src/repl/mod.rs
  src/typecheck/mod.rs
  tests/pass/typechecking.ncl
Labels: merge-queue

#551 [Refactor] Break eval into submodules
  src/error.rs
  src/eval/callstack.rs
  src/eval/lazy.rs
  src/eval/merge.rs
  src/eval/mod.rs
  src/eval/operation.rs
  src/eval/stack.rs
  src/eval/tests.rs
  src/label.rs
  src/lib.rs
  src/transform/mod.rs
Labels: merge-queue

#570 [language server] Fix resolving definition for meta
  lsp/nls/src/linearization/completed.rs
Labels: merge-queue

#591 Merge enum variants properly
  src/eval/merge.rs
  tests/pass/records.ncl
Labels: merge-queue

#593 [Language Server] Automatically manage scope_ids
  lsp/nls/src/linearization/building.rs
  lsp/nls/src/linearization/completed.rs
  lsp/nls/src/linearization/mod.rs
  src/typecheck/linearization.rs
  src/typecheck/mod.rs
Labels: merge-queue
