Repository tweag/nickel, pull requests merged in 2022-10, with the labels that each got.

#856 Add language server support for type wildcards
  lsp/nls/src/linearization/mod.rs
  src/typecheck/mod.rs
Labels: type: feature request, area: typing, area: lsp

#873 Rename StaticRecord to Record
  src/label.rs
  src/parser/uniterm.rs
  src/pretty.rs
  src/transform/free_vars.rs
  src/typecheck/eq.rs
  src/typecheck/mk_typewrapper.rs
  src/typecheck/mod.rs
  src/types.rs
Labels: merge-queue

#872 [Fix] reset state for thunks on the stack
  src/eval/lazy.rs
  src/eval/mod.rs
  src/eval/stack.rs
Labels: merge-queue

#879 Fix panic when parsing invalid use of row tails
  src/parser/grammar.lalrpop
  src/parser/tests.rs
Labels: type: bug, area: syntax

#882 Fix `ln -S` mistake in documentation
  README.md
Labels: type: documentation

#890 Fix wrong header links in merging doc page
  doc/manual/merging.md
Labels: type: documentation

#895 Fix documentation example of failing merging
  doc/manual/merging.md
Labels: type: bug, type: documentation
