Repository tweag/nickel, pull requests merged in 2022-12, with the labels that each got.

#959 Fix LSP server crash when `".` is inserted into the editor
  lsp/nls/src/requests/completion.rs
Labels: type: bug, area: lsp

#918 Auto-complete for Nickel's stdlib
  lsp/nls/src/cache.rs
  lsp/nls/src/files.rs
  lsp/nls/src/linearization/building.rs
  lsp/nls/src/linearization/completed.rs
  lsp/nls/src/linearization/interface.rs
  lsp/nls/src/linearization/mod.rs
  lsp/nls/src/requests/completion.rs
  lsp/nls/src/server.rs
  src/cache.rs
  src/stdlib.rs
  src/typecheck/linearization.rs
  src/typecheck/mod.rs
Labels: type: feature request, area: lsp

#977 Add manual section on recursive priorities
  doc/manual/merging.md
Labels: merge-queue

#980 Bump to 0.3.0
  Cargo.lock
  Cargo.toml
  RELEASES.md
  lsp/nls/Cargo.toml
  nickel-wasm-repl/Cargo.toml
  utilities/Cargo.toml
Labels: type: documentation

#981 Fix unresolved references in documentation
  src/cache.rs
  src/error.rs
  src/eval/mod.rs
  src/eval/operation.rs
  src/parser/uniterm.rs
  src/repl/query_print.rs
  src/term.rs
  src/typecheck/eq.rs
  src/typecheck/mod.rs
  src/typecheck/reporting.rs
Labels: type: documentation

#982 Update roadmap for 0.3
  README.md
  doc/manual/introduction.md
Labels: type: documentation

#991 Fix LSP server not giving completion when a non-contract meta-information is present in a declaration
  lsp/nls/src/requests/completion.rs
Labels: type: bug, area: lsp
