Repository tweag/nickel, pull requests merged in 2022-02, with the labels that each got.

#616 Uniterm
  examples/config-gcc/config-gcc.ncl
  examples/record-contract/record-contract.ncl
  examples/simple-contracts/simple-contract-bool.ncl
  examples/simple-contracts/simple-contract-div.ncl
  src/grammar.lalrpop
  src/identifier.rs
  src/parser/lexer.rs
  src/parser/uniterm.rs
  src/parser/utils.rs
  src/position.rs
  src/typecheck/error.rs
  src/typecheck/mod.rs
  src/types.rs
  stdlib/builtins.ncl
  stdlib/lists.ncl
  stdlib/strings.ncl
  tests/basics_fail.rs
  tests/contracts_fail.rs
  tests/pass/annotations.ncl
  tests/pass/basics.ncl
  tests/pass/builtins.ncl
  tests/pass/complete.ncl
  tests/pass/contracts.ncl
  tests/pass/eq.ncl
  tests/pass/functions.ncl
  tests/pass/import.ncl
  tests/pass/imported.ncl
  tests/pass/lists.ncl
  tests/pass/metavalues.ncl
  tests/pass/overriding.ncl
  tests/pass/record-defs.ncl
  tests/pass/records.ncl
  tests/pass/serialize-package.ncl
  tests/pass/serialize.ncl
  tests/pass/strings.ncl
  tests/pass/typechecking.ncl
  tests/pass/types.ncl
  tests/typecheck_fail.rs
  tests/unbound_type_variables.rs
Labels: merge-queue, area: syntax

#621 [Language Server] Remove debug info in hover overlays
  lsp/nls/src/requests/hover.rs
Labels: merge-queue

#618 [Doc] Update doc and comments to use the uniterm syntax
  benches/lists/fold.ncl
  doc/manual/syntax.md
  doc/manual/types-vs-contracts.md
  doc/manual/typing.md
  stdlib/contracts.ncl
  stdlib/lists.ncl
  stdlib/nums.ncl
  stdlib/strings.ncl
Labels: type: documentation
