Repository tweag/nickel, pull requests merged in 2023-03, with the labels that each got.

#1139 Improve contract violation error UX
  src/error.rs
  src/eval/callstack.rs
  src/program.rs
  src/repl/wasm_frontend.rs
Labels: merge-queue

#1156 Add primops to access the current diagnostic of a label
  benches/mantis/lib.ncl
  doc/manual/contracts.md
  examples/config-gcc/config-gcc.ncl
  lsp/nls/src/requests/completion.rs
  src/eval/merge.rs
  src/eval/operation.rs
  src/label.rs
  src/parser/grammar.lalrpop
  src/parser/lexer.rs
  src/term/mod.rs
  src/typecheck/operation.rs
  stdlib/array.ncl
  stdlib/builtin.ncl
  stdlib/contract.ncl
  stdlib/internals.ncl
  stdlib/num.ncl
  stdlib/string.ncl
  tests/snapshot/README.md
  tests/snapshot/inputs/errors/contract_with_custom_diagnostic.ncl
  tests/snapshot/inputs/errors/subcontract_nested_custom_diagnostics.ncl
  tests/snapshot/snapshots/snapshot__error_contract_with_custom_diagnostic.ncl.snap
  tests/snapshot/snapshots/snapshot__error_subcontract_nested_custom_diagnostics.ncl.snap
Labels: merge-queue

#1165 Use a custom debug instance for Closure
  src/eval/mod.rs
Labels: merge-queue

#1173 Fix typo in the manual (commad->command)
  doc/manual/merging.md
Labels: type: documentation, merge-queue

#1172 Add documentation for symbolic strings
  doc/manual/syntax.md
Labels: merge-queue

#1182 Use arbitrary precision rationals as the underlying representation of numbers
  Cargo.lock
  Cargo.toml
  benches/arrays.rs
  doc/manual/syntax.md
  doc/manual/typing.md
  src/deserialize.rs
  src/eval/merge.rs
  src/eval/operation.rs
  src/eval/tests.rs
  src/parser/grammar.lalrpop
  src/parser/lexer.rs
  src/parser/tests.rs
  src/parser/utils.rs
  src/pretty.rs
  src/program.rs
  src/serialize.rs
  src/term/mod.rs
  stdlib/number.ncl
  tests/integration/imports.rs
  tests/integration/query.rs
Labels: merge-queue

#1211 Implement the record_lazy_assume primop
  src/eval/fixpoint.rs
  src/eval/merge.rs
  src/eval/operation.rs
  src/identifier.rs
  src/parser/grammar.lalrpop
  src/parser/lexer.rs
  src/term/mod.rs
  src/transform/desugar_destructuring.rs
  src/typecheck/operation.rs
  stdlib/internals.ncl
Labels: merge-queue

#1191 Fix LSP crash when a resolved import term fails to typecheck
  lsp/nls/src/cache.rs
Labels: type: bug, area: lsp

#1198 Reformat the .ncl files of the repo with Topiary
  benches/mantis/deploy-example.ncl
  benches/mantis/deploy.ncl
  benches/mantis/jobs/mantis.ncl
  benches/mantis/lib.ncl
  benches/mantis/run.ncl
  benches/mantis/schemas/nomad/types.ncl
  benches/mantis/tasks/promtail.ncl
  benches/mantis/tasks/telegraf.ncl
  stdlib/array.ncl
  stdlib/builtin.ncl
  stdlib/contract.ncl
  stdlib/enum.ncl
  stdlib/function.ncl
  stdlib/internals.ncl
  stdlib/number.ncl
  stdlib/record.ncl
  stdlib/string.ncl
Labels: merge-queue

#1213 Update `contract.Equal` to be lazy on record
  stdlib/contract.ncl
  stdlib/internals.ncl
Labels: merge-queue
